### ISSUE TITLE
Raspi+GmediaRenderer+BubbleUPnP to play video?

### ISSUE THREAD

**Issue by imu1254** [hzeller/gmrender-resurrect#62]
Hi all,can someone with knowlege test it because it works for me exellent.
Here is what I've done:
http://paste.ubuntu.com/7449701/

**Comment by Madhu205** [comment]
I followed what you say,but in my case I am using upnp av control point instead of bubble upnp. I was unable to play videos on raspberry. Did you try with upnp av control point(linux)? 

Is there any difference in both control points, as for documents the control point just instruct the render to play the media content but here videos are playing with bubble upnp and upnp av control point unable to do that. What may be the reason?

**Comment by daryltucker** [comment]
Can someone please re-post that paste publicly?
